"""Group table  migration

Revision ID: 2e703aaca786
Revises: 203c10ffede0
Create Date: 2025-07-08 11:16:28.243695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e703aaca786'
down_revision = '203c10ffede0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('groups_name_key'), type_='unique')
        batch_op.drop_column('name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint(batch_op.f('users_role_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['group_id'], ['group_id'])
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_role_id_fkey'), 'roles', ['role_id'], ['role_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('group_id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('groups_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    op.create_table('roles_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('roles_users_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('roles_users_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('roles_users_pkey'))
    )
    # ### end Alembic commands ###
