"""Add role_id or group_id to User

Revision ID: 4c35003da2da
Revises: 9bc1923969d1
Create Date: 2025-07-08 00:33:10.504013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c35003da2da'
down_revision = '9bc1923969d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_group_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['role_id'])
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_group_id_fkey'), 'groups', ['group_id'], ['group_id'])
        batch_op.drop_column('role_id')

    op.drop_table('roles_users')
    # ### end Alembic commands ###
